# Generated by Django 2.2.5 on 2019-10-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_credentials',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
